apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      component: server
  template:  
    metadata: 
      labels:  
        component: server
    spec: 
      containers: 
        - name: server
          image: mohijeetsinh/server
          ports:
            - containerPort: 5000
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: database-1.c5guysmykg2l.us-east-1.rds.amazonaws.com
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres 
            - name: PGPASSWORD
              value: PGPASSWORD

        

            

